#!/usr/bin/env ruby

require 'rubygems'
require 'exiftoolr'
require 'findler'

class Findler::Filters
  def self.with_exif(children)
    child_files = children.select { |ea| ea.file? }
    child_dirs = children.select { |ea| ea.directory? }
    e = Exiftoolr.new(child_files)
    good = e.files_with_results
    bad = child_files - good
    puts "Files missing EXIF:\n  #{(bad).join("\n  ")}" unless bad.empty?
    good + child_dirs
  end
end

f = Findler.new(ENV['HOME'])
f.add_extensions ".jpg", ".jpeg", ".cr2", ".nef"
f.add_filter :with_exif
f.case_insensitive!
iter = f.iterator

while nxt = iter.next_file
  puts "next file: #{nxt}"
end
